jobs:
  - job: ExtractAndCopyAssets
    dependsOn: start_containers
    displayName: Extract And Copy Assets
    steps:
      - script: |
          CONTAINER_ID=$(APP_NAME)_$(CI_COMMIT_SHORT_SHA)
          docker cp "$CONTAINER_ID:/app/public/assets" $(Build.SourcesDirectory)/public/assets
        displayName: 'Extract Assets To Public Folder'
        condition: succeededOrFailed()

      - publish: $(Build.SourcesDirectory)/public/assets
        artifact: Aquaflow_Assets
        displayName: 'Publish Assets'
        continueOnError: true
