stages:
- stage: PublishArtifact
  displayName: Publish Deploy Artifact
  jobs:
    - job: Publish
      steps:
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(Build.SourcesDirectory)'
            Contents: |
              **
              !**/private/**
              !vendor/bundle/**
              !**/coverage/**
              !**/node_modules/**
              !**/tmp/**
              !**/log/**
              !**/.git/**
              !**/.gitlab/**
              !**/.yardoc/**
              !**/.yarn/**
              tmp/pids/**
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'drop'
            publishLocation: 'Container'
