jobs:
  - job: start_containers
    displayName: Start Containers
    steps:
      - script: |
          docker compose -p $(APP_NAME)_$(CI_COMMIT_SHORT_SHA) up -d --no-recreate
        displayName: Start the Docker containers
